### ISSUE TITLE
WIN32OLE error in Linux

### ISSUE THREAD

**Issue by funnyphone** [ruby/win32ole#3]
hi，all

I‘m not sure if WIN32OLE can be run in Linux.  
Since it can be installed in Linux, just suppose that it can be run.

Code:
###############################
require 'win32ole'

excel = WIN32OLE.new('Excel.Application')
###############################
When I run the sample ruby sample code listed in README.md (Ver 1.8.8), following error is shown:
: uninitialized constant WIN32OLE (NameError)  

Could you please tell me how to fix it?

Thank you very much.

**Comment by funnyphone** [comment]
I searched the whole root folder (/) , and found that there is no win32ole.so,  Is this normal?

**Comment by nobu** [comment]
WIN32OLE is only for Windows as its name.

**Comment by funnyphone** [comment]
> WIN32OLE is only for Windows as its name.

Thank you very much!
